'use client';
import {useEffect,useState} from 'react';
import {Upload,Mail,FileText,Download,CheckCircle2,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {categories,type Finding} from '@/lib/document-checks';
import {readDocument} from '@/lib/document-reader';
type Doc={id:string;filename:string;mime:string;size:number;category:string;source:string;source_message_id:string;read_status:string;read_note:string;review_status:string;extracted_text:string;findings:Finding[]};
type Data={documents:Doc[];required:string[];rulesConfigured:boolean;branch:string;checklist:{category:string;state:string}[]};
const readLabel:Record<string,string>={pending:'Henüz okunmadı',read:'Metin okundu',partial:'Kısmi okuma',unreadable:'Okunamadı'};
const reviewLabel:Record<string,string>={pending:'Kontrol bekliyor',accepted:'Broker kontrol etti',needs_attention:'Düzeltme gerekiyor'};
export default function DocumentsPanel({quoteId,onBusy}:{quoteId:string;onBusy:(busy:boolean)=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[message,setMessage]=useState(''),[category,setCategory]=useState('Diğer'),[rules,setRules]=useState<string[]>([]),[editingRules,setEditingRules]=useState(false);
 async function load(){const r=await fetch('/api/documents?quoteId='+quoteId);if(!r.ok)throw Error('Evraklar yüklenemedi. Yeniden deneyin.');const d=await r.json() as Data;setData(d);setRules(d.required);return d}
 useEffect(()=>{let alive=true;fetch('/api/documents?quoteId='+quoteId).then(async r=>{if(!r.ok)throw Error();const d=await r.json() as Data;if(alive){setData(d);setRules(d.required)}}).catch(()=>{if(alive)setError('Evraklar yüklenemedi. Yeniden deneyin.')});return()=>{alive=false}},[quoteId]);
 async function job(fn:()=>Promise<void>){setBusy(true);onBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı. Yeniden deneyin.')}finally{setBusy(false);onBusy(false);setProgress('')}}
 async function patch(body:object){const r=await fetch('/api/documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const e=await r.json() as {error?:string};throw Error(e.error||'Kontrol kaydedilemedi')}}
 async function analyze(id:string,file:File){const reading=await readDocument(file,setProgress);await patch({id,action:'reading',...reading})}
 async function upload(file:File,source='Yükleme',sourceMessageId=''){
  if(file.size>10*1024*1024)throw Error(file.name+': Dosya 10 MB sınırını aşıyor.');setProgress(file.name+' kaydediliyor…');const form=new FormData();form.append('file',file);form.append('quoteId',quoteId);form.append('category',category);form.append('source',source.slice(0,500));form.append('sourceMessageId',sourceMessageId.slice(0,300));const r=await fetch('/api/documents',{method:'POST',body:form});const result=await r.json() as {id:string;duplicate:boolean;error?:string};if(!r.ok)throw Error(result.error||'Dosya yüklenemedi');if(!result.duplicate)await analyze(result.id,file);return result.duplicate as boolean;
 }
 async function filesChosen(files:File[],email:boolean){if(!files.length)return;await job(async()=>{
  let queue:{file:File;source:string;messageId:string}[]=[],skipped=0,duplicate=0,added=0;const failures:string[]=[];
  if(email){const file=files[0];if(file.size>20*1024*1024)throw Error('E-posta dosyası en fazla 20 MB olabilir.');setProgress('E-posta ekleri ayrılıyor…');const {default:PostalMime}=await import('postal-mime');const parsed=await PostalMime.parse(await file.arrayBuffer(),{maxNestingDepth:20,maxHeadersSize:100000});for(const a of parsed.attachments){if(a.disposition==='inline'&&a.related){skipped++;continue}if(!['application/pdf','image/png','image/jpeg','image/webp'].includes(a.mimeType)){skipped++;continue}queue.push({file:new File([a.content as ArrayBuffer],a.filename||'belge',{type:a.mimeType}),source:'E-posta: '+(parsed.subject||'(konusuz)')+' — '+(parsed.from?.address||''),messageId:parsed.messageId||''})}if(!queue.length)throw Error('Bu e-postada desteklenen PDF veya görsel eki bulunamadı.');
  }else{queue=files.map(file=>({file,source:'Yükleme',messageId:''}))}
  if(queue.length>10)throw Error('Tek seferde en fazla 10 belge ekleyebilirsiniz.');
  for(const item of queue){try{if(await upload(item.file,item.source,item.messageId))duplicate++;else added++}catch(e){failures.push(item.file.name+': '+(e instanceof Error?e.message:'İşlem başarısız'))}}
  await load();setMessage(`${added} belge eklendi.${duplicate?' '+duplicate+' aynı dosya zaten kayıtlı.':''}${skipped?' '+skipped+' desteklenmeyen veya satır içi ek atlandı.':''}`);if(failures.length)setError(failures.join('\n'));
 })}
 return <section className="documents-panel" aria-label="Evraklar ve kontrol"><div className="document-intro"><div><h3>Evraklar ve kontrol</h3><p>Dosyayı ekle, içeriği karşılaştır, sonucu kontrol et.</p></div><span className="document-count">{data?.documents.length??0} belge</span></div>
 <div className="upload-box"><label className="document-label">Yüklenecek evrak türü<Select value={category} onValueChange={setCategory} disabled={busy}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></label><div className="upload-actions"><label className={'upload-button '+(busy?'disabled':'')}><Upload size={18}/> Belge yükle<input aria-label="PDF veya görsel yükle" disabled={busy} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" multiple onChange={e=>{const f=Array.from(e.target.files||[]);e.target.value='';void filesChosen(f,false)}}/></label><label className={'upload-button secondary-upload '+(busy?'disabled':'')}><Mail size={18}/> E-posta eklerini al<input aria-label="EML dosyasından ekleri al" disabled={busy} type="file" accept=".eml,message/rfc822" onChange={e=>{const f=Array.from(e.target.files||[]);e.target.value='';void filesChosen(f,true)}}/></label></div><p>PDF, JPG, PNG, WebP · Belge başına 10 MB · Tek seferde 10 belge</p><details><summary>E-posta eklerini nasıl eklerim?</summary><p>Gmail’de e-postayı açıp üç nokta menüsünden “İletiyi indir” seçeneğini kullan. İndirdiğin .eml dosyasını burada seç; PDF ve görsel ekleri bu işe eklensin. Otomatik Gmail / n8n bağlantısı kapalı.</p></details></div>
 {busy&&<p className="doc-progress" role="status">{progress||'Kaydediliyor…'} Bu pencereyi işlem bitene kadar açık tut.</p>}{message&&<p className="doc-success" role="status">{message}</p>}{error&&<div className="doc-error" role="alert">{error}<Button disabled={busy} variant="outline" onClick={()=>job(async()=>{await load()})}>Yeniden yükle</Button></div>}
 {data&&<><div className="checklist-heading"><h4>{data.branch} evrak listesi</h4><Button variant="ghost" size="sm" disabled={busy} onClick={()=>setEditingRules(!editingRules)}>{editingRules?'Kapat':'Listeyi düzenle'}</Button></div>{!data.rulesConfigured&&<p className="doc-hint">Bu branş için istenecek evraklar henüz belirlenmedi. Brokerın kullandığı listeyi seç.</p>}{editingRules&&<div className="rules-editor"><p>Seçimler bütün {data.branch} işlerine uygulanır. Bu liste yasal veya şirket bazlı zorunluluk listesi değildir.</p>{categories.map(c=><label key={c}><Checkbox disabled={busy} checked={rules.includes(c)} onCheckedChange={v=>setRules(v?[...rules,c]:rules.filter(x=>x!==c))}/>{c}</label>)}<Button disabled={busy} onClick={()=>job(async()=>{const r=await fetch('/api/document-rules',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({branch:data.branch,categories:rules})});if(!r.ok)throw Error('Liste kaydedilemedi.');await load();setEditingRules(false);setMessage('Branşın evrak listesi kaydedildi.')})}>Listeyi kaydet</Button></div>}
 <div className="document-checklist">{data.checklist.map(c=><div key={c.category}><span>{c.category}</span><span className={'check-state '+c.state}>{c.state==='missing'?'Eksik':c.state==='review'?'Geldi · kontrol bekliyor':'Kontrol edildi'}</span></div>)}{data.rulesConfigured&&!data.checklist.length&&<p className="doc-hint">Bu branş için zorunlu evrak seçilmedi.</p>}</div>
 {!data.documents.length&&<div className="documents-empty"><FileText size={28}/><p>Bu işe henüz evrak eklenmedi.</p></div>}
 <div className="document-list">{data.documents.map(d=><article className="document-card" key={d.id}><div className="document-card-head"><FileText size={22}/><div><strong>{d.filename}</strong><small>{Math.ceil(d.size/1024)} KB · {d.source}</small></div><a className="download-link" href={'/api/documents/file?id='+d.id} aria-label={d.filename+' indir'}><Download size={18}/></a></div><div className="document-badges"><span className={d.read_status==='read'?'read-ok':'read-warning'}>{readLabel[d.read_status]}</span><span>{reviewLabel[d.review_status]}</span></div><div className="document-controls"><Select value={d.category} disabled={busy} onValueChange={v=>job(async()=>{await patch({id:d.id,action:'category',category:v});await load()})}><SelectTrigger aria-label={d.filename+' evrak türü'}><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" disabled={busy} onClick={()=>job(async()=>{setProgress('Belge açılıyor…');const r=await fetch('/api/documents/file?id='+d.id);if(!r.ok)throw Error('Belge alınamadı.');await analyze(d.id,new File([await r.blob()],d.filename,{type:d.mime}));await load();setMessage('Belge yeniden okundu; broker kontrolü bekleniyor.')})}>Yeniden oku</Button></div>
 <div className="findings">{d.findings.map((f,i)=><div className={'finding '+f.state} key={i}>{f.state==='match'?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}<div><strong>{f.field}: {f.state==='match'?'Eşleşiyor':f.state==='mismatch'?'Uyuşmuyor':'Kontrol gerekli'}</strong><p>{f.value}</p>{f.state==='mismatch'&&<p>Teklif kaydı: {f.expected}</p>}</div></div>)}</div><p className="doc-hint">{d.read_note||'Belge henüz okunmadı.'}</p><details><summary>Okunan metin</summary><pre>{d.extracted_text||'Okunabilir metin yok.'}</pre></details><div className="review-actions"><Button size="sm" disabled={busy||d.review_status==='accepted'} onClick={()=>job(async()=>{await patch({id:d.id,action:'review',status:'accepted'});await load()})}>Gözle kontrol ettim</Button><Button size="sm" variant="outline" disabled={busy||d.review_status==='needs_attention'} onClick={()=>job(async()=>{await patch({id:d.id,action:'review',status:'needs_attention'});await load()})}>Düzeltme gerekiyor</Button></div></article>)}</div></>}
 <p className="doc-footnote">Okuma PDF metni ve Türkçe OCR ile yapılır. Etiketli müşteri, şirket ve TL tutarı karşılaştırılır; belgenin gerçekliği veya teminat yeterliliği doğrulanmaz. Taramalarda hata olabilir. Otomatik karşılaştırma broker onayı yerine geçmez.</p></section>
}
