import {database} from '@/lib/quotes-db';
import {isResponse,requireApiUser} from '@/lib/api-auth';
const states=['Bekliyor','İnceleniyor','Onaylandı','Poliçeleşti','Reddedildi'];
const branches=['Kasko','Trafik','Sağlık','Konut','İşyeri','Diğer'];
export async function GET(){const user=await requireApiUser();if(isResponse(user))return user;try{const result=await database().prepare('SELECT * FROM quotes WHERE owner_id=? ORDER BY createdAt DESC').bind(user.userId).all();return Response.json(result.results,{headers:{'Cache-Control':'no-store'}})}catch(e){console.error('Quote load failed',e);return Response.json({error:'Teklifler yüklenemedi'},{status:503})}}
async function save(request:Request,update:boolean){
const user=await requireApiUser();if(isResponse(user))return user;
const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)return Response.json({error:'Geçersiz kaynak'},{status:403});
let q:any;try{const raw=await request.text();if(raw.length>12000)throw Error();q=JSON.parse(raw);if(!q||['agency','customer','insurer'].some(k=>typeof q[k]!=='string'||!q[k].trim()||q[k].length>160)||!branches.includes(q.branch)||!states.includes(q.status)||typeof q.amount!=='number'||!Number.isFinite(q.amount)||q.amount<=0||q.amount>999999999||typeof q.notes!=='string'||q.notes.length>3000||(update&&(typeof q.id!=='string'||!/^[a-f0-9-]{36}$/.test(q.id))))throw Error()}catch{return Response.json({error:'Teklif bilgilerini kontrol edin'},{status:400})}
try{const id=update?q.id:crypto.randomUUID();const values=[q.agency.trim(),q.customer.trim(),q.insurer.trim(),q.branch,Math.round(q.amount*100)/100,q.status,q.notes];if(update){const owned=await database().prepare('SELECT id FROM quotes WHERE id=? AND owner_id=?').bind(id,user.userId).first();if(!owned)return Response.json({error:'Teklif bulunamadı'},{status:404});await database().batch([database().prepare("UPDATE documents SET review_status='pending' WHERE quote_id=? AND EXISTS (SELECT 1 FROM quotes WHERE id=? AND owner_id=? AND (customer<>? OR insurer<>? OR amount<>? OR branch<>?))").bind(id,id,user.userId,q.customer.trim(),q.insurer.trim(),Math.round(q.amount*100)/100,q.branch),database().prepare('UPDATE quotes SET agency=?,customer=?,insurer=?,branch=?,amount=?,status=?,notes=? WHERE id=? AND owner_id=?').bind(...values,id,user.userId)])}else{await database().prepare('INSERT INTO quotes (agency,customer,insurer,branch,amount,status,notes,id,owner_id,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(...values,id,user.userId,new Date().toISOString()).run()}return Response.json({id},{status:update?200:201})}catch(e){console.error('Quote save failed',e);return Response.json({error:'Kaydedilemedi'},{status:503})}}
export async function POST(r:Request){return save(r,false)}
export async function PATCH(r:Request){return save(r,true)}
